In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('thyroidDF.csv')

In [3]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ...    TT4  \
0           f               f              f                 t  ...    NaN   
1           f               f              f                 f  ...  128.0   
2           f               f              f                 f  ...    NaN   
3           f               f              f                 f  ...    NaN   
4           f               f              f                 f  ...    NaN   
...       ...             ...            ...               ...  ...    ...   
9167        f               f              f                 f  ...   64.0   
9168        f               f              f                 f  ...   91.0   
9169        f               f              f                 f  ...  113.0   
9170        f               f              f                 f  ...   75.0   
9171        f               f              f                 t  ...   66.0   

     T4U_measured   T4U FTI_measured   FTI TBG_measured   TBG  \
0               f   NaN            f   NaN            f   NaN   
1               f   NaN            f   NaN            f   NaN   
2               f   NaN            f   NaN            t  11.0   
3               f   NaN            f   NaN            t  26.0   
4               f   NaN            f   NaN            t  36.0   
...           ...   ...          ...   ...          ...   ...   
9167            t  0.83            t  77.0            f   NaN   
9168            t  0.92            t  99.0            f   NaN   
9169            t  1.27            t  89.0            f   NaN   
9170            t  0.85            t  88.0            f   NaN   
9171            t  1.02            t  65.0            f   NaN   

      referral_source target  patient_id  
0               other      -   840801013  
1               other      -   840801014  
2               other      -   840801042  
3               other      -   840803046  
4               other      S   840803047  
...               ...    ...         ...  
9167              SVI      -   870119022  
9168              SVI      -   870119023  
9169              SVI      I   870119025  
9170            other      -   870119027  
9171            other      -   870119035  

[9172 rows x 31 columns]

In [4]:
df.head(20)

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick pregnant  \
0    29   F            f                  f                   f    f        f   
1    29   F            f                  f                   f    f        f   
2    41   F            f                  f                   f    f        f   
3    36   F            f                  f                   f    f        f   
4    32   F            f                  f                   f    f        f   
5    60   F            f                  f                   f    f        f   
6    77   F            f                  f                   f    f        f   
7    28   F            f                  f                   f    f        f   
8    28   F            f                  f                   f    f        f   
9    28   F            f                  f                   f    f        f   
10   54   F            f                  f                   f    f        f   
11   42   F            f                  f                   f    f        f   
12   51   M            t                  f                   f    f        f   
13   51   F            f                  f                   f    f        f   
14   37   F            f                  f                   f    f        f   
15   16   M            f                  f                   f    f        f   
16   54   F            f                  f                   f    f        f   
17   43   M            f                  f                   f    f        f   
18   63   F            t                  f                   f    t        f   
19   36   F            f                  f                   f    f        f   

   thyroid_surgery I131_treatment query_hypothyroid  ...    TT4 T4U_measured  \
0                f              f                 t  ...    NaN            f   
1                f              f                 f  ...  128.0            f   
2                f              f                 f  ...    NaN            f   
3                f              f                 f  ...    NaN            f   
4                f              f                 f  ...    NaN            f   
5                f              f                 f  ...    NaN            f   
6                f              f                 f  ...    NaN            f   
7                f              f                 f  ...  116.0            f   
8                f              f                 f  ...   76.0            f   
9                f              f                 f  ...   83.0            f   
10               f              f                 f  ...  133.0            f   
11               f              f                 f  ...  105.0            f   
12               f              f                 f  ...    NaN            f   
13               f              f                 f  ...  116.0            f   
14               f              f                 f  ...    NaN            f   
15               f              f                 f  ...    NaN            f   
16               f              f                 f  ...  122.0            f   
17               f              f                 f  ...  116.0            f   
18               f              f                 f  ...   48.0            t   
19               f              f                 t  ...   90.0            t   

     T4U FTI_measured   FTI TBG_measured   TBG  referral_source target  \
0    NaN            f   NaN            f   NaN            other      -   
1    NaN            f   NaN            f   NaN            other      -   
2    NaN            f   NaN            t  11.0            other      -   
3    NaN            f   NaN            t  26.0            other      -   
4    NaN            f   NaN            t  36.0            other      S   
5    NaN            f   NaN            t  26.0            other      -   
6    NaN            f   NaN            t  21.0            other      -   
7    NaN            f   NaN  

In [5]:
print(df.head(20))

    age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick pregnant  \
0    29   F            f                  f                   f    f        f   
1    29   F            f                  f                   f    f        f   
2    41   F            f                  f                   f    f        f   
3    36   F            f                  f                   f    f        f   
4    32   F            f                  f                   f    f        f   
5    60   F            f                  f                   f    f        f   
6    77   F            f                  f                   f    f        f   
7    28   F            f                  f                   f    f        f   
8    28   F            f                  f                   f    f        f   
9    28   F            f                  f                   f    f        f   
10   54   F            f                  f                   f    f        f   
11   42   F            f    

In [6]:
df.shape
row, columns = df.shape
print(f'Total number of rows is: {row}')
print(f'Total number of columns is : {columns}')

Total number of rows is: 9172
Total number of columns is : 31


In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
9167    False
9168    False
9169    False
9170    False
9171    False
Length: 9172, dtype: bool

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isna()

age    sex  on_thyroxine  query_on_thyroxine  on_antithyroid_meds  \
0     False  False         False               False                False   
1     False  False         False               False                False   
2     False  False         False               False                False   
3     False  False         False               False                False   
4     False  False         False               False                False   
...     ...    ...           ...                 ...                  ...   
9167  False  False         False               False                False   
9168  False  False         False               False                False   
9169  False  False         False               False                False   
9170  False  False         False               False                False   
9171  False  False         False               False                False   

       sick  pregnant  thyroid_surgery  I131_treatment  query_hypothyroid  \
0     False     False            False           False              False   
1     False     False            False           False              False   
2     False     False            False           False              False   
3     False     False            False           False              False   
4     False     False            False           False              False   
...     ...       ...              ...             ...                ...   
9167  False     False            False           False              False   
9168  False     False            False           False              False   
9169  False     False            False           False              False   
9170  False     False            False           False              False   
9171  False     False            False           False              False   

      ...    TT4  T4U_measured    T4U  FTI_measured    FTI  TBG_measured  \
0     ...   True         False   True         False   True         False   
1     ...  False         False   True         False   True         False   
2     ...   True         False   True         False   True         False   
3     ...   True         False   True         False   True         False   
4     ...   True         False   True         False   True         False   
...   ...    ...           ...    ...           ...    ...           ...   
9167  ...  False         False  False         False  False         False   
9168  ...  False         False  False         False  False         False   
9169  ...  False         False  False         False  False         False   
9170  ...  False         False  False         False  False         False   
9171  ...  False         False  False         False  False         False   

        TBG  referral_source  target  patient_id  
0      True            False   False       False  
1      True            False   False       False  
2     False            False   False       False  
3     False            False   False       False  
4     False            False   False       False  
...     ...              ...     ...         ...  
9167   True            False   False       False  
9168   True            False   False       False  
9169   True            False   False       False  
9170   True            False   False       False  
9171   True            False   False       False  

[9172 rows x 31 columns]

In [10]:
df.isna().sum()

age                       0
sex                     307
on_thyroxine              0
query_on_thyroxine        0
on_antithyroid_meds       0
sick                      0
pregnant                  0
thyroid_surgery           0
I131_treatment            0
query_hypothyroid         0
query_hyperthyroid        0
lithium                   0
goitre                    0
tumor                     0
hypopituitary             0
psych                     0
TSH_measured              0
TSH                     842
T3_measured               0
T3                     2604
TT4_measured              0
TT4                     442
T4U_measured              0
T4U                     809
FTI_measured              0
FTI                     802
TBG_measured              0
TBG                    8823
referral_source           0
target                    0
patient_id                0
dtype: int64

In [11]:
print(df.isna().sum())

age                       0
sex                     307
on_thyroxine              0
query_on_thyroxine        0
on_antithyroid_meds       0
sick                      0
pregnant                  0
thyroid_surgery           0
I131_treatment            0
query_hypothyroid         0
query_hyperthyroid        0
lithium                   0
goitre                    0
tumor                     0
hypopituitary             0
psych                     0
TSH_measured              0
TSH                     842
T3_measured               0
T3                     2604
TT4_measured              0
TT4                     442
T4U_measured              0
T4U                     809
FTI_measured              0
FTI                     802
TBG_measured              0
TBG                    8823
referral_source           0
target                    0
patient_id                0
dtype: int64


In [12]:
df.describe()

age          TSH           T3          TT4          T4U  \
count   9172.000000  8330.000000  6568.000000  8730.000000  8363.000000   
mean      73.555822     5.218403     1.970629   108.700305     0.976056   
std     1183.976718    24.184006     0.887579    37.522670     0.200360   
min        1.000000     0.005000     0.050000     2.000000     0.170000   
25%       37.000000     0.460000     1.500000    87.000000     0.860000   
50%       55.000000     1.400000     1.900000   104.000000     0.960000   
75%       68.000000     2.700000     2.300000   126.000000     1.065000   
max    65526.000000   530.000000    18.000000   600.000000     2.330000   

               FTI         TBG    patient_id  
count  8370.000000  349.000000  9.172000e+03  
mean    113.640746   29.870057  8.529473e+08  
std      41.551650   21.080504  7.581969e+06  
min       1.400000    0.100000  8.408010e+08  
25%      93.000000   21.000000  8.504090e+08  
50%     109.000000   26.000000  8.510040e+08  
75%     128.000000   31.000000  8.607110e+08  
max     881.000000  200.000000  8.701190e+08

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9172 entries, 0 to 9171
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  9172 non-null   int64  
 1   sex                  8865 non-null   object 
 2   on_thyroxine         9172 non-null   object 
 3   query_on_thyroxine   9172 non-null   object 
 4   on_antithyroid_meds  9172 non-null   object 
 5   sick                 9172 non-null   object 
 6   pregnant             9172 non-null   object 
 7   thyroid_surgery      9172 non-null   object 
 8   I131_treatment       9172 non-null   object 
 9   query_hypothyroid    9172 non-null   object 
 10  query_hyperthyroid   9172 non-null   object 
 11  lithium              9172 non-null   object 
 12  goitre               9172 non-null   object 
 13  tumor                9172 non-null   object 
 14  hypopituitary        9172 non-null   object 
 15  psych                9172 non-null   o

In [14]:
df['sex'].unique()

array(['F', 'M', nan], dtype=object)

In [15]:
df['sex'].value_counts()

sex
F    6073
M    2792
Name: count, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9172 entries, 0 to 9171
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  9172 non-null   int64  
 1   sex                  8865 non-null   object 
 2   on_thyroxine         9172 non-null   object 
 3   query_on_thyroxine   9172 non-null   object 
 4   on_antithyroid_meds  9172 non-null   object 
 5   sick                 9172 non-null   object 
 6   pregnant             9172 non-null   object 
 7   thyroid_surgery      9172 non-null   object 
 8   I131_treatment       9172 non-null   object 
 9   query_hypothyroid    9172 non-null   object 
 10  query_hyperthyroid   9172 non-null   object 
 11  lithium              9172 non-null   object 
 12  goitre               9172 non-null   object 
 13  tumor                9172 non-null   object 
 14  hypopituitary        9172 non-null   object 
 15  psych                9172 non-null   o

In [17]:
df['TSH_measured'].unique()

array(['t', 'f'], dtype=object)

In [18]:
df['TSH'][df['TSH_measured'] == 'f'].unique()

array([nan])

In [19]:
df['TSH'][df['TSH_measured'] == 'f'].isnull().sum()

np.int64(842)

In [20]:
df['TSH'].isnull().sum()

np.int64(842)

In [21]:
df['T3_measured'].unique()

array(['f', 't'], dtype=object)

In [22]:
df['T3'][df['T3_measured'] == 'f'].unique()

array([nan])

In [23]:
df['T3'][df['T3_measured'] == 'f'].isnull().sum()

np.int64(2604)

In [24]:
df['T3'].isnull().sum()

np.int64(2604)

In [25]:
df['TT4_measured'].unique()

array(['f', 't'], dtype=object)

In [26]:
df['TT4'][df['TT4_measured'] == 'f'].unique()

array([nan])

In [27]:
df['TT4'][df['TT4_measured'] == 'f'].isnull().sum()

np.int64(442)

In [28]:
df['TT4'].isnull().sum()

np.int64(442)

In [29]:
df['T4U_measured'].unique()

array(['f', 't'], dtype=object)

In [30]:
df['T4U'][df['T4U_measured'] == 'f'].unique()

array([nan])

In [31]:
df['T4U'][df['T4U_measured'] == 'f'].isnull().sum()

np.int64(809)

In [32]:
df['T4U'].isnull().sum()

np.int64(809)

In [33]:
df['FTI_measured'].unique()

array(['f', 't'], dtype=object)

In [34]:
df['FTI'][df['FTI_measured'] == 'f'].unique()

array([nan])

In [35]:
df['FTI'][df['FTI_measured'] == 'f'].isnull().sum()

np.int64(802)

In [36]:
df['FTI'].isnull().sum()

np.int64(802)

In [37]:
df['TBG_measured'].unique()

array(['f', 't'], dtype=object)

In [38]:
df['TBG'][df['TBG_measured'] == 'f'].unique()

array([nan])

In [39]:
df['TBG'][df['TBG_measured'] == 'f'].isnull().sum()

np.int64(8823)

In [40]:
df['TBG'].isnull().sum()

np.int64(8823)

In [41]:
df['age'].unique()

array([   29,    41,    36,    32,    60,    77,    28,    54,    42,
          51,    37,    16,    43,    63,    40,    75,    56,    85,
          71,    67,    55,    61,    46,    44,    82,    64,    70,
          33,    59,    53,    52,    49,    35,    48,    27,    69,
          76,    73,    68,    66,    30,    88,    38,    58,    21,
          45,    83,    62,    25,    86,    72,    14,    15,    39,
          26,    20,    80,    90,    23,    18,    13,    78,    24,
          81,    92,    57,    74,     9,    47,    17,    11,    50,
          34,     8,    79,    31,    65,    84,    12,    10,    19,
          22,     1,     2,    97,     6,    89,    87,   455,    93,
           7,    91,     5,    94,     4, 65511,    95, 65512,     3,
       65526])

In [42]:
df.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_meds', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH_measured', 'TSH',
       'T3_measured', 'T3', 'TT4_measured', 'TT4', 'T4U_measured', 'T4U',
       'FTI_measured', 'FTI', 'TBG_measured', 'TBG', 'referral_source',
       'target', 'patient_id'],
      dtype='object')

In [43]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ...    TT4  \
0           f               f              f                 t  ...    NaN   
1           f               f              f                 f  ...  128.0   
2           f               f              f                 f  ...    NaN   
3           f               f              f                 f  ...    NaN   
4           f               f              f                 f  ...    NaN   
...       ...             ...            ...               ...  ...    ...   
9167        f               f              f                 f  ...   64.0   
9168        f               f              f                 f  ...   91.0   
9169        f               f              f                 f  ...  113.0   
9170        f               f              f                 f  ...   75.0   
9171        f               f              f                 t  ...   66.0   

     T4U_measured   T4U FTI_measured   FTI TBG_measured   TBG  \
0               f   NaN            f   NaN            f   NaN   
1               f   NaN            f   NaN            f   NaN   
2               f   NaN            f   NaN            t  11.0   
3               f   NaN            f   NaN            t  26.0   
4               f   NaN            f   NaN            t  36.0   
...           ...   ...          ...   ...          ...   ...   
9167            t  0.83            t  77.0            f   NaN   
9168            t  0.92            t  99.0            f   NaN   
9169            t  1.27            t  89.0            f   NaN   
9170            t  0.85            t  88.0            f   NaN   
9171            t  1.02            t  65.0            f   NaN   

      referral_source target  patient_id  
0               other      -   840801013  
1               other      -   840801014  
2               other      -   840801042  
3               other      -   840803046  
4               other      S   840803047  
...               ...    ...         ...  
9167              SVI      -   870119022  
9168              SVI      -   870119023  
9169              SVI      I   870119025  
9170            other      -   870119027  
9171            other      -   870119035  

[9172 rows x 31 columns]

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [45]:
df.drop(columns=['TSH_measured', 'T3_measured', 'TT4_measured', 'T4U_measured', 'FTI_measured', 'TBG_measured', 'patient_id', 'TBG'], inplace=True)
df.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_meds', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U',
       'FTI', 'referral_source', 'target'],
      dtype='object')

In [46]:
df.shape

(9172, 23)

In [47]:
df['target'].unique()

array(['-', 'S', 'F', 'AK', 'R', 'I', 'M', 'N', 'G', 'K', 'A', 'KJ', 'L',
       'MK', 'Q', 'J', 'C|I', 'O', 'LJ', 'H|K', 'D', 'GK', 'MI', 'P',
       'FK', 'B', 'GI', 'C', 'GKJ', 'OI', 'D|R', 'E'], dtype=object)

In [49]:
df['target']

0       -
1       -
2       -
3       -
4       S
       ..
9167    -
9168    -
9169    I
9170    -
9171    -
Name: target, Length: 9172, dtype: object

In [50]:
col_with_null = ['TSH', 'T3', 'TT4', 'T4U', 'FTI']
for col in col_with_null:
    df[col] = df[col].fillna(0)

In [51]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ... tumor  \
0           f               f              f                 t  ...     f   
1           f               f              f                 f  ...     f   
2           f               f              f                 f  ...     f   
3           f               f              f                 f  ...     f   
4           f               f              f                 f  ...     f   
...       ...             ...            ...               ...  ...   ...   
9167        f               f              f                 f  ...     f   
9168        f               f              f                 f  ...     f   
9169        f               f              f                 f  ...     f   
9170        f               f              f                 f  ...     f   
9171        f               f              f                 t  ...     f   

     hypopituitary psych  TSH   T3    TT4   T4U   FTI  referral_source  target  
0                f     f  0.3  0.0    0.0  0.00   0.0            other       -  
1                f     f  1.6  1.9  128.0  0.00   0.0            other       -  
2                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
3                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
4                f     f  0.0  0.0    0.0  0.00   0.0            other       S  
...            ...   ...  ...  ...    ...   ...   ...              ...     ...  
9167             f     f  0.0  0.0   64.0  0.83  77.0              SVI       -  
9168             f     f  0.0  0.0   91.0  0.92  99.0              SVI       -  
9169             f     f  0.0  0.0  113.0  1.27  89.0              SVI       I  
9170             f     f  0.0  0.0   75.0  0.85  88.0            other       -  
9171             f     f  0.0  0.0   66.0  1.02  65.0            other       -  

[9172 rows x 23 columns]

In [52]:
df.isnull().sum()

age                      0
sex                    307
on_thyroxine             0
query_on_thyroxine       0
on_antithyroid_meds      0
sick                     0
pregnant                 0
thyroid_surgery          0
I131_treatment           0
query_hypothyroid        0
query_hyperthyroid       0
lithium                  0
goitre                   0
tumor                    0
hypopituitary            0
psych                    0
TSH                      0
T3                       0
TT4                      0
T4U                      0
FTI                      0
referral_source          0
target                   0
dtype: int64

In [53]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ... tumor  \
0           f               f              f                 t  ...     f   
1           f               f              f                 f  ...     f   
2           f               f              f                 f  ...     f   
3           f               f              f                 f  ...     f   
4           f               f              f                 f  ...     f   
...       ...             ...            ...               ...  ...   ...   
9167        f               f              f                 f  ...     f   
9168        f               f              f                 f  ...     f   
9169        f               f              f                 f  ...     f   
9170        f               f              f                 f  ...     f   
9171        f               f              f                 t  ...     f   

     hypopituitary psych  TSH   T3    TT4   T4U   FTI  referral_source  target  
0                f     f  0.3  0.0    0.0  0.00   0.0            other       -  
1                f     f  1.6  1.9  128.0  0.00   0.0            other       -  
2                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
3                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
4                f     f  0.0  0.0    0.0  0.00   0.0            other       S  
...            ...   ...  ...  ...    ...   ...   ...              ...     ...  
9167             f     f  0.0  0.0   64.0  0.83  77.0              SVI       -  
9168             f     f  0.0  0.0   91.0  0.92  99.0              SVI       -  
9169             f     f  0.0  0.0  113.0  1.27  89.0              SVI       I  
9170             f     f  0.0  0.0   75.0  0.85  88.0            other       -  
9171             f     f  0.0  0.0   66.0  1.02  65.0            other       -  

[9172 rows x 23 columns]

In [54]:
sex_mode = df['sex'].mode()[0]
sex_mode

'F'

In [55]:
df['sex'] = df['sex'].fillna(sex_mode)
df['sex'].isna().sum()

np.int64(0)

In [56]:
df.isnull().sum()

age                    0
sex                    0
on_thyroxine           0
query_on_thyroxine     0
on_antithyroid_meds    0
sick                   0
pregnant               0
thyroid_surgery        0
I131_treatment         0
query_hypothyroid      0
query_hyperthyroid     0
lithium                0
goitre                 0
tumor                  0
hypopituitary          0
psych                  0
TSH                    0
T3                     0
TT4                    0
T4U                    0
FTI                    0
referral_source        0
target                 0
dtype: int64

In [57]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ... tumor  \
0           f               f              f                 t  ...     f   
1           f               f              f                 f  ...     f   
2           f               f              f                 f  ...     f   
3           f               f              f                 f  ...     f   
4           f               f              f                 f  ...     f   
...       ...             ...            ...               ...  ...   ...   
9167        f               f              f                 f  ...     f   
9168        f               f              f                 f  ...     f   
9169        f               f              f                 f  ...     f   
9170        f               f              f                 f  ...     f   
9171        f               f              f                 t  ...     f   

     hypopituitary psych  TSH   T3    TT4   T4U   FTI  referral_source  target  
0                f     f  0.3  0.0    0.0  0.00   0.0            other       -  
1                f     f  1.6  1.9  128.0  0.00   0.0            other       -  
2                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
3                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
4                f     f  0.0  0.0    0.0  0.00   0.0            other       S  
...            ...   ...  ...  ...    ...   ...   ...              ...     ...  
9167             f     f  0.0  0.0   64.0  0.83  77.0              SVI       -  
9168             f     f  0.0  0.0   91.0  0.92  99.0              SVI       -  
9169             f     f  0.0  0.0  113.0  1.27  89.0              SVI       I  
9170             f     f  0.0  0.0   75.0  0.85  88.0            other       -  
9171             f     f  0.0  0.0   66.0  1.02  65.0            other       -  

[9172 rows x 23 columns]

In [58]:
for i in df.columns:
    if df[i].dtype == 'object':
        print(f'Unique values in {i}: {df[i].unique()}')

Unique values in sex: ['F' 'M']
Unique values in on_thyroxine: ['f' 't']
Unique values in query_on_thyroxine: ['f' 't']
Unique values in on_antithyroid_meds: ['f' 't']
Unique values in sick: ['f' 't']
Unique values in pregnant: ['f' 't']
Unique values in thyroid_surgery: ['f' 't']
Unique values in I131_treatment: ['f' 't']
Unique values in query_hypothyroid: ['t' 'f']
Unique values in query_hyperthyroid: ['f' 't']
Unique values in lithium: ['f' 't']
Unique values in goitre: ['f' 't']
Unique values in tumor: ['f' 't']
Unique values in hypopituitary: ['f' 't']
Unique values in psych: ['f' 't']
Unique values in referral_source: ['other' 'SVI' 'SVHC' 'STMW' 'SVHD' 'WEST']
Unique values in target: ['-' 'S' 'F' 'AK' 'R' 'I' 'M' 'N' 'G' 'K' 'A' 'KJ' 'L' 'MK' 'Q' 'J' 'C|I'
 'O' 'LJ' 'H|K' 'D' 'GK' 'MI' 'P' 'FK' 'B' 'GI' 'C' 'GKJ' 'OI' 'D|R' 'E']


In [59]:
df.shape

(9172, 23)

In [60]:
df['hypopituitary'].unique()

array(['f', 't'], dtype=object)

In [61]:
df['age'].unique()

array([   29,    41,    36,    32,    60,    77,    28,    54,    42,
          51,    37,    16,    43,    63,    40,    75,    56,    85,
          71,    67,    55,    61,    46,    44,    82,    64,    70,
          33,    59,    53,    52,    49,    35,    48,    27,    69,
          76,    73,    68,    66,    30,    88,    38,    58,    21,
          45,    83,    62,    25,    86,    72,    14,    15,    39,
          26,    20,    80,    90,    23,    18,    13,    78,    24,
          81,    92,    57,    74,     9,    47,    17,    11,    50,
          34,     8,    79,    31,    65,    84,    12,    10,    19,
          22,     1,     2,    97,     6,    89,    87,   455,    93,
           7,    91,     5,    94,     4, 65511,    95, 65512,     3,
       65526])

In [62]:
df = df[df['age'] <= 100]

In [63]:
df['age'].unique()

array([29, 41, 36, 32, 60, 77, 28, 54, 42, 51, 37, 16, 43, 63, 40, 75, 56,
       85, 71, 67, 55, 61, 46, 44, 82, 64, 70, 33, 59, 53, 52, 49, 35, 48,
       27, 69, 76, 73, 68, 66, 30, 88, 38, 58, 21, 45, 83, 62, 25, 86, 72,
       14, 15, 39, 26, 20, 80, 90, 23, 18, 13, 78, 24, 81, 92, 57, 74,  9,
       47, 17, 11, 50, 34,  8, 79, 31, 65, 84, 12, 10, 19, 22,  1,  2, 97,
        6, 89, 87, 93,  7, 91,  5, 94,  4, 95,  3])

In [64]:
df[(df['sex']=='Male') & (df['pregnant'] == 't')]

Empty DataFrame
Columns: [age, sex, on_thyroxine, query_on_thyroxine, on_antithyroid_meds, sick, pregnant, thyroid_surgery, I131_treatment, query_hypothyroid, query_hyperthyroid, lithium, goitre, tumor, hypopituitary, psych, TSH, T3, TT4, T4U, FTI, referral_source, target]
Index: []

[0 rows x 23 columns]

In [65]:
df1 = df.copy()

In [66]:
df1.to_csv('thyroid_cleaned.csv', index=False)

In [67]:
df

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick  \
0      29   F            f                  f                   f    f   
1      29   F            f                  f                   f    f   
2      41   F            f                  f                   f    f   
3      36   F            f                  f                   f    f   
4      32   F            f                  f                   f    f   
...   ...  ..          ...                ...                 ...  ...   
9167   56   M            f                  f                   f    f   
9168   22   M            f                  f                   f    f   
9169   69   M            f                  f                   f    f   
9170   47   F            f                  f                   f    f   
9171   31   M            f                  f                   f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ... tumor  \
0           f               f              f                 t  ...     f   
1           f               f              f                 f  ...     f   
2           f               f              f                 f  ...     f   
3           f               f              f                 f  ...     f   
4           f               f              f                 f  ...     f   
...       ...             ...            ...               ...  ...   ...   
9167        f               f              f                 f  ...     f   
9168        f               f              f                 f  ...     f   
9169        f               f              f                 f  ...     f   
9170        f               f              f                 f  ...     f   
9171        f               f              f                 t  ...     f   

     hypopituitary psych  TSH   T3    TT4   T4U   FTI  referral_source  target  
0                f     f  0.3  0.0    0.0  0.00   0.0            other       -  
1                f     f  1.6  1.9  128.0  0.00   0.0            other       -  
2                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
3                f     f  0.0  0.0    0.0  0.00   0.0            other       -  
4                f     f  0.0  0.0    0.0  0.00   0.0            other       S  
...            ...   ...  ...  ...    ...   ...   ...              ...     ...  
9167             f     f  0.0  0.0   64.0  0.83  77.0              SVI       -  
9168             f     f  0.0  0.0   91.0  0.92  99.0              SVI       -  
9169             f     f  0.0  0.0  113.0  1.27  89.0              SVI       I  
9170             f     f  0.0  0.0   75.0  0.85  88.0            other       -  
9171             f     f  0.0  0.0   66.0  1.02  65.0            other       -  

[9168 rows x 23 columns]

In [ ]:
df1